pipeline {
    agent any 
    stages {
        stage('Build') { 
//            steps {
//                build job: 'ut'
//                build job: 'kt'
//            }
            try {
                build job: 'ut'
                build job: 'kt'
            }
            catch (Exception e){
                error "build failed!!"
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }    
}
